### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by chris-dalrymple** [arve0/download-size#5]
NodeJS version 6.9.5
NPM version 4.1.2
OS: Windows 10
Installed download-size globally, as instructions suggest. Every time I run it, regardless of package, returns the following syntax error.

async function main () {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by arve0** [comment]
Node 6 is not supported as of now.
